# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Count integer points in the cross polytope
#'
#' @description This method counts the integer points in 
#' the \eqn{r}th dilitation
#' of the \eqn{n}th dimensional cross-polytope. 
#' \deqn{ \{v\in Z^n: \sum_{i=1}^n|v_i|\le r \}}
#' The cardinality of this set is given by the formula
#' \deqn{\sum_{k=0}^n\binom{n}{k}\cdot\binom{r-k+n}{n}}
#'
#' @param dim integer
#' @param r integer 
#' @return the number of integer points in the cross polytope defined by
#' constMat and rhs. The number is returned in a character string.
#' @name countCrossPoly
#' @references
#' \url{https://en.wikipedia.org/wiki/Cross-polytope}
#' @seealso
#' \code{\link{countIntPoints}}
#' \code{\link{countFiber}}
#' @usage
#' A<-matrix(c(1,1,1,1,1,0),2,3)
#' b<-c("14","20")
#' countIntPoints(A,b)
countCrossPoly <- function(dim, r) {
    .Call('rrSample_countCrossPoly', PACKAGE = 'rrSample', dim, r)
}

#' @title Count integer points in a polytope
#'
#' @description This method counts the integer points in a polytope defined by the
#' matrix \eqn{A} and the right-hand side vector \eqn{b}. \code{countIntPoint} 
#' uses the method \code{countFiber} of the \code{algstat} package (which is
#' done there by using \code{LattE}). 
#' 
#' @param A matrix
#' @param b CharacterVector or NumericVector
#' @return the number of integer points in the polytope defined by
#' constMat and rhs. The number is returned in a character string.
#' @name countIntPoints
#' @seealso
#' \code{\link{countCrossPoly}}
#' \code{\link{countFiber}}
#' @usage
#' A<-matrix(c(1,1,1,1,1,0),2,3)
#' b<-c("14","20")
#' countIntPoints(A,b)
countIntPoints <- function(A, b) {
    .Call('rrSample_countIntPoints', PACKAGE = 'rrSample', A, b)
}

estimateDiam <- function(initial, moves) {
    .Call('rrSample_estimateDiam', PACKAGE = 'rrSample', initial, moves)
}

estimateMixing <- function(u, constMat, moves, diam, nIntPoints = "", tol = 0.25) {
    .Call('rrSample_estimateMixing', PACKAGE = 'rrSample', u, constMat, moves, diam, nIntPoints, tol)
}

fiberWalk <- function(initial, constMat, moves, diam = 0L, length = NULL, showOutput = FALSE) {
    .Call('rrSample_fiberWalk', PACKAGE = 'rrSample', initial, constMat, moves, diam, length, showOutput)
}

sampleCrossPoly <- function(dim, r, showOutput = FALSE) {
    .Call('rrSample_sampleCrossPoly', PACKAGE = 'rrSample', dim, r, showOutput)
}

