# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

countCrossPoly <- function(dim, r) {
    .Call('rrSample_countCrossPoly', PACKAGE = 'rrSample', dim, r)
}

fiberWalk <- function(initial, moves, diam, length = 0L, showOutput = FALSE) {
    .Call('rrSample_fiberWalk', PACKAGE = 'rrSample', initial, moves, diam, length, showOutput)
}

sampleCrossPoly <- function(dim, r, showOutput = FALSE) {
    .Call('rrSample_sampleCrossPoly', PACKAGE = 'rrSample', dim, r, showOutput)
}

