# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

countCrossPoly <- function(dim, r) {
    .Call('rrSample_countCrossPoly', PACKAGE = 'rrSample', dim, r)
}

estimateDiam <- function(initial, moves) {
    .Call('rrSample_estimateDiam', PACKAGE = 'rrSample', initial, moves)
}

estimateMixing <- function(u, constMat, moves, diam, nIntPoints = 0, tol = 0.25) {
    .Call('rrSample_estimateMixing', PACKAGE = 'rrSample', u, constMat, moves, diam, nIntPoints, tol)
}

fiberWalk <- function(initial, constMat, moves, diam = 0L, length = 0, showOutput = FALSE) {
    .Call('rrSample_fiberWalk', PACKAGE = 'rrSample', initial, constMat, moves, diam, length, showOutput)
}

sampleCrossPoly <- function(dim, r, showOutput = FALSE) {
    .Call('rrSample_sampleCrossPoly', PACKAGE = 'rrSample', dim, r, showOutput)
}

